# This workflow will upload docs to the gh-pages branch whenever something is pushed to main.

name: Docs
on:
  push:
    branches:
      - main

jobs:
  upload_docs:
    name: upload docs
    runs-on: ubuntu-20.04
    env:
      GRGIT_USER: ${{ secrets.GRGIT_USER }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22
      - uses: gradle/actions/setup-gradle@v3
      - name: Publish docs with Gradle
        run: gradle gitPublishPush
