name: CI

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}

    steps:
      - run: export GRADLE_USER_HOME=`pwd`/.gradle
      - run: echo "name=RELEASE_TAG::${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Setup Java JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jvmTest
  release:
    name: Publish artifacts
    runs-on: ubuntu-20.04
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_KEY }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_USER }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.signingKey }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.signingPassword }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishAllPublicationsToMavenRepository
